name: iZone
main: net.techguard.izone.iZone
version: 1.0
description: Easy yet Complex
softdepend: [Vault, Multiverse-Core, MultiWorld, ParticleLIB]
authors:
  - TechGuard
  - TryHardDood
commands:
  izone:
    description: Prints current version
  zmod:
    description: Prints all the 'iZone' zone Commands
