name: iZone
main: net.techguard.izone.iZone
<!--version: @version@ -->
version: 1.1.1
description: Easy yet Complex
softdepend: [Vault, Multiverse-Core, MultiWorld, ParticleLIB]
authors:
  - TechGuard
  - TryHardDood
  - Cyanoure
commands:
  izone:
    description: Prints current version
  zmod:
    description: Prints all the 'iZone' zone Commands
api-version: 1.13